#! /bin/zsh

kill_thing() {
    if (pgrep -x $1); then
        # echo "sxhkd already running"
        killall $1
        # echo "killed, waiting a bit"
        sleep 0.1
    fi
}

try_source () {
    [[ ! -f "$1" ]] || source "$1"
}


# launch sxhkd
kill_thing sxhkd
sxhkd -c ~/.config/bspwm/sxhkdrc &

# define monitors
main_monitor=$(xrandr -q | grep primary | cut -f1 -d' ')
other_monitors=$(xrandr -q | grep ' connect' | grep -v primary | cut -f1 -d' ')

(( desktop_index = 0 ))
for o_m in $other_monitors; do
  bspc monitor "$o_m" -d $(( desktop_index++ ))
done

bspc monitor $main_monitor -d $(( desktop_index++ ))
while (( desktop_index < 10 )); do
  bspc monitor $main_monitor -a $(( desktop_index++ ))
done

# configure ui
bspc config border_width         2
bspc config window_gap          22

bspc config split_ratio          0.4
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config initial_polarity second_child
bspc config automatic_scheme alternate

kill_thing dunst
dunst &

try_source "$HOME/.config/bspwm/custom.sh"
