#! /bin/zsh

kill_thing() {
    if (pgrep -x $1); then
        # echo "sxhkd already running"
        killall $1
        # echo "killed, waiting a bit"
        sleep 0.1
    fi
}

kill_thing sxhkd
sxhkd -c ~/.config/bspwm/sxhkdrc &

nitrogen --restore
setxkbmap us,de
xrandr --output HDMI-0
xrandr --output DP-0 --primary --mode 2560x1440 --pos 1920x0

bspc monitor 0x00400004 -d I II III IV V
bspc monitor 0x00400002 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          22

bspc config split_ratio          0.4
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config initial_polarity first_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

kill_thing dunst
dunst &
